// ---------------------------------------------------------------------------
// Sasoo UI Strings (Korean)
// ---------------------------------------------------------------------------
// All user-facing strings in one place for consistency.
//
// Voice & tone: 해요체. 능동형·긍정형으로 쓰고, 과도한 경어('~시겠어요', '~께')와
// '{명사}+{명사}' 나열은 피한다. 다이얼로그 왼쪽 버튼은 '취소'가 아니라 '닫기'로 통일한다.
// 짧은 명사 라벨(필드명, 탭, 상태 배지)은 명사 그대로 둔다.

export const S = {
  // ── App / Navigation ──
  app: {
    name: 'Sasoo',
    subtitle: 'Research archive',
    home: '홈',
    upload: '아카이브 시작',
    library: '연구 보관함',
    profile: '연구자 프로필',
    settings: '설정',
    workbench: '워크벤치',
    collapse: '접기',
    expandSidebar: '사이드바 펼치기',
    collapseSidebar: '사이드바 접기',
  },

  // ── Profile (연구자 프로필) ──
  profile: {
    heroKicker: 'Researcher profile',
    sectionTitle: '기본 눈높이와 연구 배경',
    sectionDesc: '여기서 정한 값이 새 논문 분석의 기본값으로 쓰여요.',
  },

  // ── Levels (설명 수준) ──
  // 같은 개념(빛의 간섭)을 수준별 문체로 보여주는 프리뷰 문장. LevelSlider와
  // LevelCards가 이 값을 공유한다 - 단일 출처.
  levels: {
    elementary: {
      label: '초등학생',
      preview: '빛 두 줄기가 만나면 물결처럼 겹쳐서 더 밝아지거나 어두워져요.',
    },
    middle: {
      label: '중학생',
      preview: '두 빛의 파동이 겹치면 마루끼리 만나 밝아지고, 마루와 골이 만나 어두워집니다.',
    },
    high: {
      label: '고등학생',
      preview: '두 파동의 위상차가 0이면 보강간섭, π이면 상쇄간섭이 일어나 간섭무늬가 생깁니다.',
    },
    undergrad: {
      label: '학부생',
      preview: '두 간섭 광의 세기는 I = I₁ + I₂ + 2√(I₁I₂)cosΔφ로 위상차에 의해 결정됩니다.',
    },
    masters: {
      label: '석사생',
      preview: '가시도(visibility)는 광원의 시간·공간 결맞음에 의해 제한되며 상호결맞음 함수로 기술됩니다.',
    },
    phd: {
      label: '박사생',
      preview:
        '부분결맞음 조건에서 간섭항은 상호결맞음 함수 γ₁₂(τ)의 크기와 인수로 완전히 결정되며, van Cittert–Zernike 정리로 광원 분포와 연결됩니다.',
    },
  },

  // 연구 분야 아이콘 칩 라벨. 백엔드 analysis_context.py의 AREA_LABELS와
  // 글자 그대로 같아야 한다 - 키도 값도. 임의로 바꾸지 말 것.
  areas: {
    optics_photonics: '광학·포토닉스',
    ai_ml: 'AI·머신러닝',
    robotics_control: '로보틱스·제어',
    electrical_electronics: '전기·전자',
    computer_science: '컴퓨터과학',
    physics_math: '물리·수학',
    bio_medical: '바이오·의생명',
    other: '기타',
  } as Record<string, string>,

  // ── Home ──
  home: {
    greeting: '안녕하세요',
    subGreeting: '오늘 분석할 논문을 올려주세요.',
    quickActions: '바로가기',
    actionLibrary: '연구 보관함',
    actionLibraryDesc: '보관한 논문을 둘러봐요',
    recentPapers: '최근 논문',
    recentEmpty: '위에서 첫 논문을 올리면 여기에 쌓여요.',
    viewAll: '전체 보기',
    costTitle: '이번 달 비용',
    costOpenSettings: '자세히 보기',
    costMeta: (papers: number) => `논문 ${papers}편 분석`,
    costDelta: (delta: string) => `지난달 대비 ${delta}`,
    costEmptyMeta: '논문을 분석하면 비용이 여기에 표시돼요.',
    libraryTitle: '연구 보관함',
    libraryUnit: '편',
    libraryOpen: '보관함 열기',
  },

  // ── Upload Page ──
  upload: {
    title: '연구 아카이브를 시작하세요',
    description:
      '논문 PDF를 올리면 Sasoo가 요약, figure 인덱스, 재현 파라미터, 질문 흐름까지 한 번에 정리해요.',
    dragDrop: '논문 PDF를 여기에 놓으세요',
    browse: '파일 선택',
    pdfOnly: 'PDF만 올릴 수 있어요',
    maxSize: (size: string) => `최대 ${size}`,
    uploadBtn: '아카이브에 추가',
    uploading: (pct: number) => `보관 중... ${pct}%`,
    parsing: '논문 구조와 분야를 읽고 있어요...',
    success: '아카이브에 등록할 준비가 끝났어요',
    titleLabel: '제목',
    detectedDomain: '감지한 분야',
    detected: '(감지함)',
    openAnalyze: '열기 & 분석 시작',
    openWorkbench: '워크벤치 열기',
    handoffTitle: '워크벤치로 넘길 준비가 끝났어요',
    nextStepTitle: '다음 흐름',
    nextStepDesc: 'PDF를 확인한 뒤 분석을 시작하거나, 이미 준비한 결과를 바로 이어서 검토할 수 있어요.',
    outputsTitle: '생성되는 결과',
    outputSummary: '핵심 요약',
    outputFigures: 'Figure 인덱스',
    outputRecipe: '재현 파라미터',
    outputChat: '질문 기록',
    domainConfirm: '담당 분야 확인',
    domainConfirmHelp: '감지한 분야가 맞는지 확인하고 필요하면 다른 에이전트로 넘기세요.',
    analysisOptionsTitle: '분석 옵션',
    analysisOptionsOpenLabel: '분석 옵션 펼치기',
    analysisOptionsCloseLabel: '분석 옵션 접기',
    analysisOptionsHint: '초점과 설명 수준을 지금 맞추면 첫 분석부터 반영돼요. (선택)',
    focusChipsLabel: '분석 초점',
    focusChipsHelp: '관심 있는 부분을 골라요. 여러 개 골라도 되고, 안 골라도 돼요.',
    focusNoteLabel: '이 논문에서 특별히 궁금한 점',
    focusNoteHelper: '비워두면 균형 있게 분석해요',
    focusNotePlaceholder: '예: 3장의 손실 함수 유도 과정이 궁금해요',
    retry: '다시 시도',
    clear: '선택 해제',
    onlyPdf: 'PDF 파일만 올릴 수 있어요.',
    fileTooLarge: (max: string) => `파일이 너무 커요. ${max}까지 올릴 수 있어요.`,
    fileEmpty: '파일이 비어 있어요. 다른 파일을 골라 주세요.',
    uploadFailed: '논문을 보관함에 추가하지 못했어요. 잠시 후 다시 시도해 주세요.',
    heroKicker: 'Research archive for papers',
    heroPromise: '읽기 전에 구조를 세우고, 다시 찾기 전에 맥락을 남겨요.',
    heroBody: 'Sasoo는 논문을 올리자마자 분류하고, figure와 recipe를 묶어 다음 분석의 출발점을 만들어요.',
    surfaceTitle: '논문 추가',
    surfaceBody: '첫 논문을 올리면 보관함과 워크벤치가 바로 이어져요.',
    stageSelect: '파일 선택',
    stagePrepare: '분석 준비',
    stageWorkbench: '워크벤치 진입',
    outputsLead: '한 번의 업로드로 바로 이어지는 작업면',
    systemTitle: '현재 시스템 상태',
    systemReady: '연결 준비 완료',
    systemOffline: '백엔드 연결 확인 필요',
    systemLibrary: '보관 경로',
    systemAuto: '자동 분석',
    systemTheme: '테마',
    systemConfigured: '설정됨',
    systemNotConfigured: '확인 필요',
    systemAutoOn: '업로드 후 바로 분석',
    systemAutoOff: '수동으로 분석 시작',
    emptyHint: '드래그하거나 파일을 고르면 여기서 바로 다음 단계가 열려요.',
    surfaceActionTitle: '지금 바로 PDF를 올리세요',
    recentAnalyses: '최근 작업',
    recentAnalysesEmpty: '논문을 분석하면 최근 기록이 여기에 쌓여요.',
    recentLibrary: '최근 보관함',
    recentLibraryEmpty: '논문을 추가하면 보관함이 여기서부터 채워져요.',
    lastAnalyzed: '마지막 분석',
    addedLabel: '추가됨',
    openNow: '바로 열기',
    noTimestamp: '기록 없음',
  },

  // ── Workbench ──
  workbench: {
    loading: '논문을 불러오고 있어요...',
    loadFailed: '논문을 불러오지 못했어요',
    notFound: '논문을 찾지 못했어요.',
    showPdf: 'PDF 표시',
    hidePdf: 'PDF 숨기기',
    pdfFocus: 'PDF 중심',
    even: '균등',
    analysisFocus: '분석 중심',
    startAnalysis: '분석 시작',
    reAnalyze: '재분석',
    analyzing: '분석 중...',
    cancel: '취소',
    panelResize: '패널 크기 조절',
    backToLibrary: '라이브러리',
    assistant: '질문 도우미',
    assistantWaiting: 'PDF 텍스트를 다 읽으면 질문할 수 있어요',
    statusRailTitle: '분석 상태',
    inspectNow: '지금 검토하기',
    inspectClaim: '핵심 주장 보기',
    inspectFigures: '주요 Figure 보기',
    inspectTables: '주요 Table 보기',
    inspectRecipe: '재현 파라미터 확인',
    summaryTab: '요약',
    figuresTab: '그림',
    tablesTab: '표',
    recipeTab: '레시피',
    experimentTab: '실험 계획',
    experimentPending: '레시피가 준비되면 실험 계획서를 만들 수 있어요.',
  },

  // ── PDF Viewer ──
  pdf: {
    loading: 'PDF를 불러오고 있어요...',
    loadFailed: 'PDF를 불러오지 못했어요',
  },

  // ── Explanation Level Slider ──
  explanationLevel: {
    title: '설명 수준',
    help: '슬라이더를 움직여 초등학생부터 박사생까지 원하는 눈높이로 설명을 맞춰요.',
  },

  // ── Library ──
  library: {
    title: '연구 보관함',
    paperCount: (n: number) => `총 ${n}건`,
    searchPlaceholder: '제목, 저자, DOI, 키워드 검색',
    filters: '분류 도구',
    clearAll: '전체 해제',
    domain: '분야',
    allDomains: '모든 분야',
    year: '연도',
    anyYear: '모든 연도',
    status: '상태',
    allStatuses: '모든 상태',
    tags: '태그',
    allTags: '모든 태그',
    noTags: '태그 없음',
    loading: '보관함을 정리하고 있어요...',
    gridView: '그리드 보기',
    listView: '리스트 보기',
    // Sort
    newestFirst: '최신순',
    oldestFirst: '오래된순',
    titleAZ: '제목 A-Z',
    titleZA: '제목 Z-A',
    yearNewest: '연도 (최신)',
    yearOldest: '연도 (오래된)',
    recentlyAnalyzed: '최근 분석순',
    // Pagination
    showing: (from: number, to: number, total: number) =>
      `전체 ${total}건 중 ${from}-${to}`,
    recentActivity: '최근 활동',
    openedFromLibrary: '워크벤치 열기',
    continueAnalysis: '계속 분석',
    reviewError: '상태 확인',
    more: '더 보기',
    prevPage: '이전 페이지',
    nextPage: '다음 페이지',
    // Empty
    noMatch: '지금 조건에 맞는 기록이 없어요',
    noPapers: '보관함이 아직 비어 있어요',
    noMatchDesc: '조건을 조금 넓히거나 검색어를 다르게 바꾸면 다른 기록을 찾을 수 있어요.',
    noPapersDesc:
      '첫 논문을 추가하면 최근 분석, 설명 수준, 주요 상태가 이 선반에 쌓이기 시작해요.',
    clearFilters: '필터 초기화',
    // Delete modal
    deleteTitle: '논문을 삭제할까요?',
    deleteWarning: '한 번 삭제하면 되돌릴 수 없어요.',
    deleteDetails: '아래 항목을 함께 삭제해요',
    deleteItem1: 'PDF 파일과 추출한 그림 전부',
    deleteItem2: '분석 결과와 메타데이터',
    deleteItem3: '라이브러리 폴더에 있는 관련 파일',
    cancelBtn: '닫기',
    deleteBtn: '영구 삭제',
    deleting: '삭제 중...',
    delete: '삭제',
    paperId: (id: string) => `논문 ID: ${id}`,
    heroKicker: 'Archive view',
    heroBody: '검색과 필터를 먼저 보고, 목록은 바로 아래에서 시작해요.',
    collectionCount: '보관된 기록',
    collectionReady: '분석 완료',
    collectionActive: '최근 활동',
    toolsTitle: '탐색 도구',
    toolsBody: '지금 보관함에 있는 논문 기준으로 필요한 조건만 빠르게 좁혀요.',
    emptyCta: '첫 논문 추가하러 가기',
    shelfTitle: '지식 선반',
  },

  // ── Settings ──
  settings: {
    title: '설정',
    description: '보관함 위치, 분석 기본값, 모델 키를 한 곳에서 조정해요.',
    save: '변경 저장',
    saving: '저장 중...',
    saved: '저장 완료',
    discard: '되돌리기',
    loadingSettings: '제어판을 불러오고 있어요...',
    loadFailed: '설정을 불러오지 못했어요',
    saveFailed: '변경을 저장하지 못했어요',
    browseFolder: '폴더 선택',
    browseFolderFailed: '폴더 선택 창을 열지 못했어요',
    browseFolderUnavailable: '이 환경에서는 경로를 직접 입력하면 바꿀 수 있어요',
    // AI provider
    aiProvider: 'AI 공급사',
    aiProviderDesc:
      '도해 이미지 생성에 적용돼요. 논문 분석·그림 판독은 항상 Gemini로 실행되어 Gemini 키가 필요해요.',
    aiProviderOpenAI: 'OpenAI',
    aiProviderOpenAIModel: 'gpt-image-2 · 도해 생성',
    aiProviderGemini: 'Google',
    aiProviderGeminiModel: 'Nano Banana 2 · 도해 생성',
    aiProviderKeyReady: '키 등록됨',
    aiProviderKeyMissing: '키 없음',
    aiProviderSwitched: (to: string) => `${to}로 전환했습니다`,
    aiProviderLocked: 'API 키를 등록하면 분석을 시작할 수 있어요',
    // Save bar
    saveBarLabel: '변경사항',
    changeCount: (n: number) => `변경 ${n}개`,
    // API Keys
    apiKeys: '모델 키',
    geminiKey: 'Google Gemini API 키',
    openaiKey: 'OpenAI API 키',
    claudeKey: 'Anthropic Claude API 키',
    geminiHelp: 'Gemini Flash와 Gemini Pro 모델을 쓸 때 필요해요.',
    openaiHelp: 'GPT 이미지 생성(figure_gen)처럼 OpenAI 모델을 쓸 때 필요해요.',
    claudeHelp: 'Claude Sonnet으로 심층 분석할 때 필요해요.',
    getKeyAt: (name: string) => `${name}에서 키를 발급받으세요.`,
    // Researcher profile
    researcherProfile: '연구자 프로필',
    researcherProfileDesc: '분석 결과의 눈높이와 관점을 맞춰요.',
    researchContext: '연구 분야 소개',
    researchContextPlaceholder: '예: 페로브스카이트 태양전지 소자 물리를 연구해요',
    researchContextHelper: '한 줄이면 충분해요. 분석 결과가 내 분야 관점으로 이어져요.',
    defaultLevel: '기본 설명 수준',
    openProfileLink: '연구자 프로필 설정 열기',
    // Structured profile fields
    researchAreas: '주요 연구 분야',
    researchAreasHelper: '최대 3개까지 고를 수 있어요.',
    researchAreasMaxReached: '최대 3개까지 선택할 수 있어요',
    fieldExpertise: '분야 숙련도',
    readingExperience: '논문 읽기 경험',
    researchRole: '연구 역할',
    researchRolePlaceholder: '역할을 선택하세요',
    // Library
    librarySection: '보관함 경로',
    libraryPath: '논문 저장 경로',
    libraryPathHelp:
      '올린 PDF와 분석 결과를 보관하는 폴더예요. 새로 올리는 논문부터 이 경로를 쓰고, 이미 있는 논문은 원래 위치를 그대로 봐요.',
    browseFolderTitle: '라이브러리 폴더 선택',
    autoAnalyze: '업로드 후 자동 분석',
    autoAnalyzeHelp: '논문을 보관함에 추가한 뒤 곧바로 분석을 시작해요.',
    pdfParser: 'PDF 파서 엔진',
    pdfParserHelp: 'Slim 배포에는 Java 기반 OpenDataLoader를 넣었어요. Hybrid OCR 백엔드는 배포 크기가 커서 빼두었어요.',
    pdfParserJava: 'Java-only OpenDataLoader',
    extractionPipeline: 'Figure/Table 추출 경로',
    extractionPipelineHelp: '기본값은 resolver_v1이에요.',
    extractionPipelineResolverV1: 'resolver_v1 (candidate-resolver)',
    // 저장 값은 'gemini' | 'odl' 그대로다. 'gemini'는 공급사 이름이 아니라
    // "LLM 비전으로 판독" 경로를 가리키는 레거시 이름이라, 공급사 선택과
    // 혼동되지 않도록 표시 문구만 바꿨다.
    pdfVisualEngine: '그림 판독 방식',
    pdfVisualEngineHelp: 'AI 판독은 그림·수식을 정확히 읽지만 논문당 API 비용이 들어요. 빠른 추출은 무료지만 수식·표를 놓칠 수 있어요.',
    pdfVisualEngineGemini: 'AI 판독 (정확, 유료)',
    pdfVisualEngineOdl: '빠른 추출 (무료)',
    // Appearance
    appearance: '테마',
    dark: '다크',
    light: '라이트',
    // API Key status
    keyConfigured: '설정됨',
    keyNotConfigured: '미설정',
    keyUnreadable: '다시 입력해 주세요',
    keyUnreadableHelp: '저장한 키를 풀지 못했어요. 암호화 키가 사라졌거나, 다른 환경에서 저장한 키예요. 새 키를 입력하면 덮어써요.',
    enterNewKey: '새 키를 입력해 주세요...',
    // Image generation
    imageSection: '이미지 생성',
    imageSectionDesc: 'OpenAI 키와 도해(figure) 생성 옵션을 관리해요.',
    imageProvider: '도해 생성 모델',
    imageProviderOpenai: 'gpt-image-2 (기본)',
    imageProviderGemini: 'Nano Banana 2 (Gemini)',
    imageQuality: '도해 품질',
    // Cost
    usageCosts: '사용량과 비용',
    costLoadFailed: '비용 데이터를 불러오지 못했어요',
    heroKicker: 'Settings',
    heroBody: '지금 상태를 확인하고 필요한 설정부터 바로 조정해요.',
    statusConfigured: '정상 연결',
    statusMissing: '추가 설정 필요',
    sectionEdit: '변경 입력',
  },

  // ── Cost Dashboard ──
  cost: {
    thisMonth: '이번 달 비용',
    avgPerPaper: '논문당 평균',
    totalPapers: (n: number) => `총 ${n}개 논문 분석`,
    totalTokens: '총 토큰 사용량',
    tokensIn: '입력',
    tokensOut: '출력',
    monthlyTrend: '월별 추이 (최근 6개월)',
    monthLabel: (mm: string) => `${mm}월`,
    paperCount: (n: number) => `${n}개 논문`,
    perPaperCost: '논문별 비용 (상위 10개)',
    modelBreakdown: '모델별 사용량',
    modelName: '모델',
    calls: '호출',
    cost: '비용',
    efficiencyMetrics: '절감과 검증 지표',
    cacheSavings: '캐시 절감',
    estimatedSavedCalls: (n: number) => `예상 ${n}회 절약`,
    estimatedSavedCost: (amount: string) => `${amount} 절감 추정`,
    phaseCalls: 'Phase 호출',
    tableReviewQueue: '표 검증 큐',
    repairAttempts: (n: number) => `복구 시도 ${n}건`,
    reviewRequiredCount: (n: number) => `검증 필요 ${n}건`,
    noData: '아직 분석 데이터가 없어요',
    noDataDesc: '논문을 분석하면 사용량과 비용을 여기서 볼 수 있어요.',
  },

  // ── Status badges ──
  status: {
    analyzed: '분석 완료',
    analyzing: '분석 중',
    pending: '대기',
    error: '오류',
    complete: '완료',
    running: '실행 중',
  },

  // ── Analysis Panel ──
  analysis: {
    noResults: '아직 분석 결과가 없어요',
    noResultsDesc:
      'AI 분석을 시작하면 그림 추출, 재현 파라미터, 프로세스 다이어그램까지 한눈에 볼 수 있어요.',
    progress: '분석 진행',
    phase1: 'Phase 1: 심층 논문 분석',
    phase1Desc: '방법론과 결과, 기여를 종합해서 읽어요',
    phase2: 'Phase 2: 인용 분석',
    phase2Desc: '참고문헌을 정리하고 인용 빈도를 분석해요',
    phase3: 'Phase 3: 그림 & 데이터 추출',
    phase3Desc: '그림과 표, 시각 데이터를 모두 뽑고 해석해요',
    phase4: 'Phase 4: 재현성 레시피',
    phase4Desc: '실험 파라미터와 프로토콜을 자세히 뽑아요',
    phase5: 'Phase 5: 시각화 & 종합',
    phase5Desc: '프로세스 다이어그램과 시각 요약을 만들어요',
    analyzingDots: '분석 중...',
    loadingResults: '결과를 불러오고 있어요...',
    // formatPhaseAsMarkdown labels
    md: {
      domain: '분야',
      relevance: '관련도',
      methodology: '방법론',
      complexity: '복잡도',
      experimental: '실험적',
      hasFigures: '그림 포함',
      agent: '에이전트',
      yes: '예',
      no: '아니오',
      keyTopics: '핵심 주제',
      figures: '그림',
      tables: '표',
      equations: '수식',
      diagramTypes: '다이어그램 유형',
      keyFindings: '핵심 발견',
      statisticalRedFlags: '⚠️ 통계적 Red Flags',
      redFlagSeverity: { high: '높음', medium: '보통', low: '낮음' },
      redFlagTypes: {
        no_error_bars: '오차막대 미표기',
        insufficient_n: '샘플 수 부족',
        axis_manipulation: '축 스케일 조작 의심',
        cherry_picking: 'Cherry-picking 의심',
        no_statistical_significance: '통계 유의성 미언급',
        misleading_scale: '오해 유발 스케일',
      } as Record<string, string>,
      confidence: '신뢰도',
      reproducibility: '재현성',
      parameters: '파라미터',
      paramNum: '#',
      paramName: '파라미터',
      paramValue: '값',
      paramUnit: '단위',
      paramNotes: '비고',
      materials: '재료',
      equipment: '장비',
      experimentalSteps: '실험 단계',
      criticalNotes: '핵심 주의사항',
      missingInfo: '누락된 정보',
      expectedResults: '예상 결과',
      safetyNotes: '안전 주의사항',
      novelty: '신규성',
      comparisonToPrior: '기존 연구 비교',
      strengths: '강점',
      weaknesses: '약점',
      suggestedImprovements: '개선 제안',
      practicalApplications: '실용적 적용',
      followUpQuestions: '후속 질문',
    },
  },

  // ── Progress Tracker ──
  progressTracker: {
    title: '분석 진행',
    running: '실행 중',
    complete: '완료',
  },

  // ── Figures ──
  figures: {
    title: '추출한 그림',
    noFigures: '이 논문에서 뽑은 그림이 아직 없어요.',
    preparing: 'Figure를 준비하고 있어요. 잠시 후 자동으로 새로고침해요.',
    syncing: '최신 Figure를 백그라운드에서 동기화하고 있어요.',
    partialWarning: '최신 Figure를 아직 동기화하고 있어요. 지금까지 저장한 결과를 먼저 보여줘요.',
    expertExplanation: '전문가 상세 설명',
    explanationFailed: '설명을 만들지 못했어요',
    retry: '다시 시도',
    explanationLoading: 'AI가 그림을 분석하고 있어요...',
    clickForExplanation: '그림을 누르면 AI 전문가가 자세히 설명해요.',
    prevFigure: '이전 그림',
    nextFigure: '다음 그림',
    viewGrid: '그리드',
    viewCoverflow: '커버플로우',
    close: '닫기',
    viewDetail: (name: string) => `${name} 상세 보기`,
    qualityHigh: '고화질',
    qualityMedium: '보통',
    qualityLow: '저화질',
    qualityUnknown: '알 수 없음',
    statusUncertain: '불확실',
    statusReady: '확정',
    composite: 'Composite',
    jumpToPage: 'PDF 페이지로 이동',
    pageLabel: (page: number) => `${page}페이지`,
    saveImage: '그림 저장',
    saveFailed: '그림을 저장하지 못했어요',
    childGroup: (count: number) => `서브피겨 ${count}`,
    provenanceLabel: (model: string) => `분류 ${model}`,
  },

  // ── Tables ──
  tables: {
    title: '추출한 표',
    noTables: '이 논문에서 뽑은 표가 아직 없어요.',
    preparing: 'Table을 준비하고 있어요. 잠시 후 자동으로 새로고침해요.',
    syncing: '최신 Table을 백그라운드에서 동기화하고 있어요.',
    partialWarning: '최신 Table을 아직 동기화하고 있어요. 지금까지 저장한 결과를 먼저 보여줘요.',
    confidence: (score: string) => `신뢰도 ${score}`,
    parseMethod: (method: string) => `파싱 ${method}`,
    statusUncertain: '불확실',
    statusReady: '확정',
    resolverLabel: (version: string) => `해결기 ${version}`,
    modelLabel: (model: string) => `복구 ${model}`,
    reviewRequired: '검증 필요',
    repairAttempted: '복구 시도',
    repairConfidence: (score: string) => `복구 ${score}`,
    markdownPreview: '구조화된 미리보기',
    csvAsset: 'CSV 열기',
    htmlAsset: 'HTML 열기',
    jumpToPage: 'PDF 페이지로 이동',
    pageLabel: (page: number) => `${page}페이지`,
  },

  // ── Recipe Card ──
  recipe: {
    title: '재현성 레시피',
    noRecipe: '아직 레시피를 만들지 않았어요. 분석을 실행하면 파라미터를 뽑아요.',
    exportCsv: 'CSV',
    // CSV 열 이름. 엑셀에서 사용자가 그대로 읽는 문자열이라 여기 둔다. 순서 계약은
    // lib/recipeCsv.ts의 RECIPE_CSV_HEADER가 쥔다. 이름은 검증 여부를 단정하지 않는다 —
    // "발견/주장"은 출처를 가리킬 뿐이고 검증 결과는 '검증 상태' 열 하나가 말한다(DEC-012).
    csvHeader: {
      section: '구분',
      key: '항목',
      value: '값',
      status: '검증 상태',
      method: '검증 방법',
      foundQuote: '발견 인용',
      foundPage: '발견 페이지',
      claimedQuote: '주장 인용',
      claimedPage: '주장 페이지',
    },
    exported: '내보냄',
    confidence: '신뢰도',
    reproducibility: '재현성',
    objective: '목적',
    materials: '재료',
    parameters: '파라미터',
    steps: '실험 단계',
    criticalNotes: '핵심 주의사항',
    missingInfo: '누락된 정보',
    noParams:
      '파라미터를 뽑지 못했어요. 논문에 실험 세부 정보가 적거나, Methods 섹션을 온전히 읽지 못했을 수 있어요.',
    expectedResults: '예상 결과',
    safetyNotes: '안전 주의사항',
    evidence: {
      column: '근거',
      summaryBadge: (verified: number, total: number) => `근거 확인 ${verified}/${total}`,
      notRunNotice: '이 분석 결과에는 근거 검증 기록이 없어요. 다시 분석하면 근거를 모아요.',
      verifiedQuote: '확인된 원문',
      // DEC-012 — 페이지만 어긋난 near-miss용. 검증 도장 대신 "발견"이라는 문구만 쓴다.
      foundQuote: (page: number | null) => (page != null ? `발견된 원문 (p.${page})` : '발견된 원문'),
      claimedQuote: 'LLM이 주장한 인용 (원문에서 확인되지 않음)',
      confirmedPage: (page: number) => `p.${page}에서 확인`,
      foundPage: (page: number) => `발견 위치 p.${page}`,
      candidatePage: (page: number) => `후보 위치 p.${page}`,
      claimedPageNote: (page: number) => `LLM 주장 p.${page}`,
      jump: '이 페이지로 이동',
      method: {
        exact: '축자 일치',
        normalized: '표기 정규화 일치',
        partial: '부분 일치',
      },
      status: {
        VERIFIED: '원문 확인',
        UNVERIFIED_PAGE_MISMATCH: '다른 페이지에서 발견',
        UNVERIFIED_VALUE_MISMATCH: '인용에 값이 없음',
        UNVERIFIED_INFERRED: '추론값',
        UNVERIFIED_PARTIAL: '부분 일치 — 미검증',
        UNVERIFIED_AMBIGUOUS: '위치가 모호함',
        UNVERIFIED_NOT_FOUND: '원문에서 찾지 못함',
        UNVERIFIED_NO_QUOTE: '근거 없음',
        UNVERIFIED_NO_TEXT_LAYER: '검증 불가 (텍스트 없는 PDF)',
        UNVERIFIED_STALE_SOURCE: '원문이 바뀜 — 재검증 필요',
        UNVERIFIED_ERROR: '검증 실패',
        UNVERIFIED_NOT_RUN: '검증 미실행',
      },
      disclaimer: '인용이 논문 원문에 있는지 확인한 결과예요. 값의 과학적 타당성 검증은 아니에요.',
    },
  },

  // ── Mermaid Renderer ──
  mermaid: {
    title: '프로세스 다이어그램',
    notGenerated: '아직 다이어그램을 만들지 않았어요. 분석을 끝내면 프로세스 흐름을 볼 수 있어요.',
    code: '코드',
    preview: '미리보기',
    copy: '복사',
    render: '렌더링',
    reset: '초기화',
    mermaidCode: 'Mermaid 코드',
    renderFailed: '다이어그램을 그리지 못했어요',
    errorSyntax: '다이어그램 문법에 오류가 있어요',
    errorEngine: '다이어그램 엔진을 불러오지 못했어요',
    emptyCode: '다이어그램 코드가 비어 있어요',
    styleFallback: '스타일 구문에 오류가 있어 일부 스타일을 빼고 그렸어요',
    repairing: 'AI가 다이어그램 오류를 고치고 있어요...',
    repairedNotice: '구문 오류를 자동으로 고쳤어요',
    download: '다운로드',
    downloadFailed: '다이어그램을 내려받지 못했어요',
    regenerate: '다시 생성',
    regenerating: '다시 만들고 있어요...',
    regenerateFailed: '다시 만들지 못했어요',
    exportAll: '전체 다운로드',
    exporting: '내보내고 있어요...',
    exportFailed: '시각화를 내보내지 못했어요',
    visualizations: '시각화',
    generating: '시각화를 만들고 있어요...',
    generatingTime: '1~2분 걸릴 수 있어요',
    illustrationFailed: '일러스트를 만들지 못했어요',
    generationFailed: '만들지 못했어요',
  },

  // ── Toast messages ──
  toast: {
    uploadSuccess: '논문을 보관함에 추가했어요',
    uploadFailed: '논문을 보관함에 추가하지 못했어요',
    analysisStarted: '분석을 시작했어요',
    analysisComplete: '분석을 끝냈어요',
    analysisCancelled: '분석을 취소했어요',
    analysisError: '분석하는 중에 오류가 생겼어요',
    settingsSaved: '변경을 저장했어요',
    settingsFailed: '변경을 저장하지 못했어요',
    paperDeleted: '논문을 보관함에서 삭제했어요',
    deleteFailed: '논문을 삭제하지 못했어요',
    csvExported: 'CSV 파일을 내려받았어요',
    copied: '클립보드에 복사했어요',
    domainUpdated: '분야를 바꿨어요',
    agentChanged: '담당 에이전트를 바꿨어요',
    agentChangeFailed: '에이전트를 바꾸지 못했어요',
  },

  // ── Error / Fallback ──
  error: {
    occurred: '오류가 생겼어요',
    unknown: '알 수 없는 오류가 생겼어요.',
    retry: '다시 시도',
    goHome: '홈으로 돌아가기',
    devInfo: '개발자 정보 (Development Only)',
    networkError: '네트워크 연결을 확인해 주세요.',
    apiKeyMissing: '설정에서 API 키를 입력하면 분석을 시작할 수 있어요.',
    loadPapersFailed: '논문 목록을 불러오지 못했어요',
    deletePaperFailed: '논문을 삭제하지 못했어요',
    updatePaperFailed: '논문을 업데이트하지 못했어요',
    getStatusFailed: '상태를 확인하지 못했어요',
    startAnalysisFailed: '분석을 시작하지 못했어요',
    loadAnalysisFailed: '분석 결과를 불러오지 못했어요',
  },

  // ── Agent fallback ──
  agent: {
    unknownDomain: '알 수 없는 분야',
    unknownAgent: '알 수 없는 에이전트',
    fallbackQuote: '분석을 준비하고 있어요.',
  },

  // ── Titlebar ──
  titlebar: {
    minimize: '최소화',
    maximize: '최대화',
    restore: '이전 크기로',
    close: '닫기',
  },
} as const;
