// ---------------------------------------------------------------------------
// Sasoo UI Strings (Korean)
// ---------------------------------------------------------------------------
// All user-facing strings in one place for consistency.
//
// Voice & tone: 해요체. 능동형·긍정형으로 쓰고, 과도한 경어('~시겠어요', '~께')와
// '{명사}+{명사}' 나열은 피한다. 다이얼로그 왼쪽 버튼은 '취소'가 아니라 '닫기'로 통일한다.
// 짧은 명사 라벨(필드명, 탭, 상태 배지)은 명사 그대로 둔다.

export const S = {
  // ── App / Navigation ──
  app: {
    name: 'Sasoo',
    subtitle: 'Research archive',
    home: '홈',
    upload: '아카이브 시작',
    library: '연구 보관함',
    settings: '시스템 제어',
    workbench: '워크벤치',
    collapse: '접기',
    expandSidebar: '사이드바 펼치기',
    collapseSidebar: '사이드바 접기',
  },

  // ── Home ──
  home: {
    greeting: '안녕하세요',
    subGreeting: '오늘 분석할 논문을 올려주세요.',
    quickActions: '바로가기',
    actionAgents: '에이전트 편성',
    actionAgentsDesc: '분석 에이전트를 관리해요',
    actionLibrary: '연구 보관함',
    actionLibraryDesc: '보관한 논문을 둘러봐요',
    recentAnalyses: '최근 분석',
    recentLibrary: '최근 추가',
    recentEmpty: '위에서 첫 논문을 올리면 여기에 쌓여요.',
    costTitle: '이번 달 비용',
    costOpenSettings: '자세히 보기',
  },

  // ── Upload Page ──
  upload: {
    title: '연구 아카이브를 시작하세요',
    description:
      '논문 PDF를 올리면 Sasoo가 요약, figure 인덱스, 재현 파라미터, 질문 흐름까지 한 번에 정리해요.',
    dragDrop: '논문 PDF를 여기에 놓으세요',
    browse: '파일 선택',
    pdfOnly: 'PDF만 올릴 수 있어요',
    maxSize: (size: string) => `최대 ${size}`,
    uploadBtn: '아카이브에 추가',
    uploading: (pct: number) => `보관 중... ${pct}%`,
    parsing: '논문 구조와 분야를 읽고 있어요...',
    success: '아카이브에 등록할 준비가 끝났어요',
    titleLabel: '제목',
    detectedDomain: '감지한 분야',
    detected: '(감지함)',
    openAnalyze: '열기 & 분석 시작',
    openWorkbench: '워크벤치 열기',
    handoffTitle: '워크벤치로 넘길 준비가 끝났어요',
    nextStepTitle: '다음 흐름',
    nextStepDesc: 'PDF를 확인한 뒤 분석을 시작하거나, 이미 준비한 결과를 바로 이어서 검토할 수 있어요.',
    outputsTitle: '생성되는 결과',
    outputSummary: '핵심 요약',
    outputFigures: 'Figure 인덱스',
    outputRecipe: '재현 파라미터',
    outputChat: '질문 기록',
    domainConfirm: '담당 분야 확인',
    domainConfirmHelp: '감지한 분야가 맞는지 확인하고 필요하면 다른 에이전트로 넘기세요.',
    analysisOptionsTitle: '분석 옵션',
    analysisOptionsOpenLabel: '분석 옵션 펼치기',
    analysisOptionsCloseLabel: '분석 옵션 접기',
    analysisOptionsHint: '초점과 설명 수준을 지금 맞추면 첫 분석부터 반영됩니다. (선택 사항)',
    focusChipsLabel: '분석 초점',
    focusChipsHelp: '관심 있는 부분을 선택하세요. 복수 선택 가능하며, 선택하지 않아도 됩니다.',
    focusNoteLabel: '이 논문에서 특별히 궁금한 점',
    focusNoteHelper: '비워두면 균형 있게 분석합니다',
    focusNotePlaceholder: '예: 3장의 손실 함수 유도 과정이 궁금합니다',
    retry: '다시 시도',
    clear: '선택 해제',
    onlyPdf: 'PDF 파일만 올릴 수 있어요.',
    fileTooLarge: (max: string) => `파일이 너무 커요. ${max}까지 올릴 수 있어요.`,
    fileEmpty: '파일이 비어 있어요. 다른 파일을 골라 주세요.',
    uploadFailed: '논문을 보관함에 추가하지 못했어요. 잠시 후 다시 시도해 주세요.',
    heroKicker: 'Research archive for papers',
    heroPromise: '읽기 전에 구조를 세우고, 다시 찾기 전에 맥락을 남겨요.',
    heroBody: 'Sasoo는 논문을 올리자마자 분류하고, figure와 recipe를 묶어 다음 분석의 출발점을 만들어요.',
    surfaceTitle: '논문 추가',
    surfaceBody: '첫 논문을 올리면 보관함과 워크벤치가 바로 이어져요.',
    stageSelect: '파일 선택',
    stagePrepare: '분석 준비',
    stageWorkbench: '워크벤치 진입',
    outputsLead: '한 번의 업로드로 바로 이어지는 작업면',
    systemTitle: '현재 시스템 상태',
    systemReady: '연결 준비 완료',
    systemOffline: '백엔드 연결 확인 필요',
    systemLibrary: '보관 경로',
    systemAuto: '자동 분석',
    systemTheme: '테마',
    systemConfigured: '설정됨',
    systemNotConfigured: '확인 필요',
    systemAutoOn: '업로드 후 바로 분석',
    systemAutoOff: '수동으로 분석 시작',
    emptyHint: '드래그하거나 파일을 고르면 여기서 바로 다음 단계가 열려요.',
    surfaceActionTitle: '지금 바로 PDF를 올리세요',
    recentAnalyses: '최근 작업',
    recentAnalysesEmpty: '논문을 분석하면 최근 기록이 여기에 쌓여요.',
    recentLibrary: '최근 보관함',
    recentLibraryEmpty: '논문을 추가하면 보관함이 여기서부터 채워져요.',
    lastAnalyzed: '마지막 분석',
    addedLabel: '추가됨',
    openNow: '바로 열기',
    noTimestamp: '기록 없음',
  },

  // ── Workbench ──
  workbench: {
    loading: '논문을 불러오고 있어요...',
    loadFailed: '논문을 불러오지 못했어요',
    notFound: '논문을 찾지 못했어요.',
    showPdf: 'PDF 표시',
    hidePdf: 'PDF 숨기기',
    pdfFocus: 'PDF 중심',
    even: '균등',
    analysisFocus: '분석 중심',
    startAnalysis: '분석 시작',
    reAnalyze: '재분석',
    analyzing: '분석 중...',
    cancel: '취소',
    panelResize: '패널 크기 조절',
    backToLibrary: '라이브러리',
    assistant: '질문 도우미',
    assistantWaiting: 'PDF 텍스트를 다 읽으면 질문할 수 있어요',
    statusRailTitle: '분석 상태',
    inspectNow: '지금 검토하기',
    inspectClaim: '핵심 주장 보기',
    inspectFigures: '주요 Figure 보기',
    inspectTables: '주요 Table 보기',
    inspectRecipe: '재현 파라미터 확인',
    summaryTab: '요약',
    figuresTab: 'Figures',
    tablesTab: 'Tables',
    recipeTab: 'Recipe',
    experimentTab: '실험계획',
    experimentPending: '레시피가 준비되면 실험 계획서를 만들 수 있어요.',
    paperbananaProfile: '분석 프로필',
    useDefaultProfile: (label: string) => `기본값 사용 (${label})`,
    paperbananaProfileHelp: 'Figure와 시각화의 품질과 속도를 어떻게 맞출지 골라요.',
  },

  // ── PDF Viewer ──
  pdf: {
    loading: 'PDF를 불러오고 있어요...',
    loadFailed: 'PDF를 불러오지 못했어요',
  },

  // ── Explanation Level Slider ──
  explanationLevel: {
    title: '설명 수준',
    help: '슬라이더를 움직여 초등학생부터 박사생까지 원하는 눈높이로 설명을 조정합니다.',
  },

  // ── Library ──
  library: {
    title: '연구 보관함',
    paperCount: (n: number) => `총 ${n}건`,
    searchPlaceholder: '제목, 저자, DOI, 키워드 검색',
    filters: '분류 도구',
    clearAll: '전체 해제',
    domain: '분야',
    allDomains: '모든 분야',
    year: '연도',
    anyYear: '모든 연도',
    status: '상태',
    allStatuses: '모든 상태',
    tags: '태그',
    allTags: '모든 태그',
    noTags: '태그 없음',
    loading: '보관함을 정리하고 있어요...',
    gridView: '그리드 보기',
    listView: '리스트 보기',
    // Sort
    newestFirst: '최신순',
    oldestFirst: '오래된순',
    titleAZ: '제목 A-Z',
    titleZA: '제목 Z-A',
    yearNewest: '연도 (최신)',
    yearOldest: '연도 (오래된)',
    recentlyAnalyzed: '최근 분석순',
    // Pagination
    showing: (from: number, to: number, total: number) =>
      `전체 ${total}건 중 ${from}-${to}`,
    recentActivity: '최근 활동',
    openedFromLibrary: '워크벤치 열기',
    continueAnalysis: '계속 분석',
    reviewError: '상태 확인',
    more: '더 보기',
    prevPage: '이전 페이지',
    nextPage: '다음 페이지',
    // Empty
    noMatch: '지금 조건에 맞는 기록이 없어요',
    noPapers: '보관함이 아직 비어 있어요',
    noMatchDesc: '조건을 조금 넓히거나 검색어를 다르게 바꾸면 다른 기록을 찾을 수 있어요.',
    noPapersDesc:
      '첫 논문을 추가하면 최근 분석, 담당 에이전트, 주요 상태가 이 선반에 쌓이기 시작해요.',
    clearFilters: '필터 초기화',
    // Delete modal
    deleteTitle: '논문을 삭제할까요?',
    deleteWarning: '한 번 삭제하면 되돌릴 수 없어요.',
    deleteDetails: '아래 항목을 함께 삭제해요',
    deleteItem1: 'PDF 파일과 추출한 그림 전부',
    deleteItem2: '분석 결과와 메타데이터',
    deleteItem3: '라이브러리 폴더에 있는 관련 파일',
    cancelBtn: '닫기',
    deleteBtn: '영구 삭제',
    deleting: '삭제 중...',
    delete: '삭제',
    paperId: (id: string) => `논문 ID: ${id}`,
    heroKicker: 'Archive view',
    heroBody: '검색과 필터를 먼저 보고, 목록은 바로 아래에서 시작해요.',
    collectionCount: '보관된 기록',
    collectionReady: '분석 완료',
    collectionActive: '최근 활동',
    toolsTitle: '탐색 도구',
    toolsBody: '지금 보관함에 있는 논문 기준으로 필요한 조건만 빠르게 좁혀요.',
    emptyCta: '첫 논문 추가하러 가기',
    shelfTitle: '지식 선반',
  },

  // ── Settings ──
  settings: {
    title: '시스템 제어',
    description: '보관함 위치, 분석 기본값, 모델 키를 한 곳에서 조정해요.',
    save: '변경 저장',
    saving: '저장 중...',
    saved: '저장 완료',
    discard: '되돌리기',
    unsavedChanges: '아직 저장하지 않은 변경이 있어요',
    loadingSettings: '제어판을 불러오고 있어요...',
    loadFailed: '설정을 불러오지 못했어요',
    saveFailed: '변경을 저장하지 못했어요',
    browseFolder: '폴더 선택',
    browseFolderFailed: '폴더 선택 창을 열지 못했어요',
    browseFolderUnavailable: '이 환경에서는 경로를 직접 입력하면 바꿀 수 있어요',
    // API Keys
    apiKeys: '모델 키',
    geminiKey: 'Google Gemini API 키',
    openaiKey: 'OpenAI API 키',
    claudeKey: 'Anthropic Claude API 키',
    geminiHelp: 'Gemini Flash와 Gemini Pro 모델을 쓸 때 필요해요.',
    openaiHelp: 'GPT 이미지 생성(figure_gen)처럼 OpenAI 모델을 쓸 때 필요해요.',
    claudeHelp: 'Claude Sonnet으로 심층 분석할 때 필요해요.',
    getKeyAt: (name: string) => `${name}에서 키를 발급받으세요.`,
    // Researcher profile
    researcherProfile: '연구자 프로필',
    researcherProfileDesc: '분석 결과의 눈높이와 관점을 조정합니다.',
    researchContext: '연구 분야 소개',
    researchContextPlaceholder: '예: 페로브스카이트 태양전지 소자 물리를 연구합니다',
    researchContextHelper: '한 줄이면 충분합니다. 분석 결과가 내 분야 관점으로 연결됩니다.',
    defaultLevel: '기본 설명 수준',
    // Library
    librarySection: '보관함 경로',
    libraryPath: '논문 저장 경로',
    libraryPathHelp:
      '올린 PDF와 분석 결과를 보관하는 폴더예요. 새로 올리는 논문부터 이 경로를 쓰고, 이미 있는 논문은 원래 위치를 그대로 봐요.',
    browseFolderTitle: '라이브러리 폴더 선택',
    autoAnalyze: '업로드 후 자동 분석',
    autoAnalyzeHelp: '논문을 보관함에 추가한 뒤 곧바로 분석을 시작해요.',
    pdfParser: 'PDF 파서 엔진',
    pdfParserHelp: 'Slim 배포에는 Java 기반 OpenDataLoader를 넣었어요. Hybrid OCR 백엔드는 배포 크기가 커서 빼두었어요.',
    pdfParserJava: 'Java-only OpenDataLoader',
    extractionPipeline: 'Figure/Table 추출 경로',
    extractionPipelineHelp: '기본값은 resolver_v1이에요. 이전 추출 경로를 그대로 써야 할 때만 legacy를 고르세요.',
    extractionPipelineLegacy: 'legacy (이전 경로)',
    extractionPipelineResolverV1: 'resolver_v1 (candidate-resolver)',
    profileFast: '빠름',
    profileBalanced: '균형',
    profileQuality: '고품질',
    // Appearance
    appearance: '표시 모드',
    dark: '다크',
    light: '라이트',
    // Density
    density: '밀도',
    densityComfortable: 'Comfortable',
    densityCompact: 'Compact',
    // API Key status
    keyConfigured: '설정됨',
    keyNotConfigured: '미설정',
    keyUnreadable: '다시 입력해 주세요',
    keyUnreadableHelp: '저장한 키를 풀지 못했어요. 암호화 키가 사라졌거나, 다른 환경에서 저장한 키예요. 새 키를 입력하면 덮어써요.',
    enterNewKey: '새 키를 입력해 주세요...',
    // Image generation
    imageProvider: '도해 생성 모델',
    imageProviderOpenai: 'gpt-image-2 (기본)',
    imageProviderGemini: 'Nano Banana 2 (Gemini)',
    imageQuality: '도해 품질',
    // Cost
    usageCosts: '사용량과 비용',
    costLoadFailed: '비용 데이터를 불러오지 못했어요',
    heroKicker: 'Control room',
    heroBody: '지금 상태를 확인하고 필요한 설정부터 바로 조정해요.',
    statusConfigured: '정상 연결',
    statusMissing: '추가 설정 필요',
    sectionCurrent: '현재 상태',
    sectionEdit: '변경 입력',
  },

  // ── Cost Dashboard ──
  cost: {
    thisMonth: '이번 달 비용',
    avgPerPaper: '논문당 평균',
    totalPapers: (n: number) => `총 ${n}개 논문 분석`,
    totalTokens: '총 토큰 사용량',
    tokensIn: '입력',
    tokensOut: '출력',
    monthlyTrend: '월별 추이 (최근 6개월)',
    monthLabel: (mm: string) => `${mm}월`,
    paperCount: (n: number) => `${n}개 논문`,
    perPaperCost: '논문별 비용 (상위 10개)',
    modelBreakdown: '모델별 사용량',
    modelName: '모델',
    calls: '호출',
    cost: '비용',
    efficiencyMetrics: '절감과 검증 지표',
    cacheSavings: '캐시 절감',
    estimatedSavedCalls: (n: number) => `예상 ${n}회 절약`,
    estimatedSavedCost: (amount: string) => `${amount} 절감 추정`,
    phaseCalls: 'Phase 호출',
    tableReviewQueue: '표 검증 큐',
    repairAttempts: (n: number) => `복구 시도 ${n}건`,
    reviewRequiredCount: (n: number) => `검증 필요 ${n}건`,
    noData: '아직 분석 데이터가 없어요',
    noDataDesc: '논문을 분석하면 사용량과 비용을 여기서 볼 수 있어요.',
  },

  // ── Agents ──
  agents: {
    title: '에이전트 편성',
    description: '각 에이전트가 어떤 논문을 맡고 어떤 관점으로 답할지 배치해요',
    guidanceTitle: '권장 편집 흐름',
    guidanceBody: '먼저 맡길 논문 범위와 답변 톤을 정하고, 고급 프롬프트는 마지막에만 조정하세요.',
    createNew: '새 에이전트',
    import_: '가져오기',
    export_: '내보내기',
    duplicate: '복제',
    delete_: '삭제',
    builtin: '기본',
    custom: '사용자',
    enabled: '활성',
    disabled: '비활성',
    edit: '편집',
    save: '저장',
    cancel: '취소',
    back: '돌아가기',
    confirmDelete: '이 에이전트를 삭제할까요?',
    cannotDeleteBuiltin: '기본 에이전트는 비활성으로 바꿔서 숨길 수 있어요.',
    overrideRemoved: '사용자 변경을 지우고 기본 버전으로 되돌렸어요.',
    agentCreated: '에이전트를 만들었어요',
    agentUpdated: '에이전트를 수정했어요',
    agentDeleted: '에이전트를 삭제했어요',
    importSuccess: '에이전트를 가져왔어요',
    exportSuccess: '에이전트를 내보냈어요',
    duplicateSuccess: '에이전트를 복제했어요',
    nameExists: '같은 이름의 에이전트가 이미 있어요. 다른 이름을 지어 주세요',
    invalidFile: '.md 파일만 가져올 수 있어요',
    // Wizard steps
    stepIdentity: '정체성',
    stepDomain: '도메인',
    stepParameters: '파라미터',
    stepPrompts: '프롬프트',
    stepPreview: '미리보기',
    // Fields
    name: '이름',
    nameHelp: '영문 소문자, 숫자, 밑줄만 쓸 수 있어요',
    displayName: '표시 이름',
    displayNameKo: '한국어 이름',
    personality: '성격',
    personalityHelp: '에이전트의 성격을 한 문장으로 설명하세요',
    quote: '대사',
    quoteHelp: '에이전트의 대표 대사',
    color: '색상',
    domain: '도메인',
    domainDisplay: '도메인 (영문)',
    domainDisplayKo: '도메인 (한국어)',
    keywords: '키워드',
    keywordsHelp: 'Enter를 누르면 추가해요. 논문을 분류할 때 써요.',
    weightedKeywords: '가중 키워드',
    weightedKeywordsHelp: '일반 키워드보다 2배 무겁게 반영해요.',
    recipeParameters: '레시피 파라미터',
    recipeParametersHelp: '이 분야에서 추출할 핵심 실험 파라미터',
    model: '모델',
    prompts: '프롬프트',
    screening: '스크리닝',
    visual: '시각 검증',
    recipe: '레시피',
    deepDive: '심층 분석',
    rawMarkdown: '마크다운 편집',
    formMode: '폼 편집',
    preview: '미리보기',
    previous: '이전',
    next: '다음',
    create: '생성',
    noAgents: '아직 편성한 에이전트가 없어요',
    noAgentsDesc: '첫 에이전트를 만들면 분야 배정과 답변 톤을 여기서부터 정리할 수 있어요.',
    papers: (n: number) => `${n}건 분석`,
    // AI generation
    aiGenerate: 'AI로 생성',
    aiGenerating: 'AI가 에이전트를 만들고 있어요...',
    aiGeneratingDesc: '연구 분야에 맞는 프로필과 프롬프트를 쓰고 있어요',
    domainDescription: '연구 분야',
    domainDescriptionPlaceholder: '예: 유기합성화학 - 촉매 반응 및 합성 경로 설계',
    domainDescriptionHelp: '이 에이전트가 주로 맡아야 할 연구 분야를 설명하세요',
    personalityHint: '성격 (선택)',
    personalityHintPlaceholder: '예: 꼼꼼하고 친절한, 직설적인',
    advancedMode: '고급 모드',
    simpleMode: 'AI 생성 모드',
    reviewTitle: '생성 결과 검토',
    reviewDesc: 'AI가 만든 초안이에요. 고치고 싶은 부분을 바꾼 뒤 저장하세요.',
    regenerate: '다시 생성',
    generateFailed: '에이전트 초안을 만들지 못했어요. 잠시 후 다시 시도해 주세요.',
    heroKicker: 'Agent routing',
    heroBody: '편성과 생성 액션부터 먼저 보고, 목록은 바로 아래에서 시작해요.',
    summaryAgents: '전체 편성',
    summaryBuiltin: '기본 프리셋',
    summaryActive: '현재 활성',
    createDirect: '직접 작성',
    createAi: 'AI 초안으로 시작',
    createChoiceBody: '직접 작성하거나 AI 초안을 받아 곧바로 다듬어요.',
    registryTitle: '편성 현황',
    registryEmptyTitle: '아직 배정 규칙이 비어 있어요',
    registryEmptyBody: '새 에이전트를 만들거나 설계 파일을 가져오면 편성 목록이 여기서부터 쌓여요.',
  },

  // ── Status badges ──
  status: {
    analyzed: '분석 완료',
    analyzing: '분석 중',
    pending: '대기',
    error: '오류',
    complete: '완료',
    running: '실행 중',
  },

  // ── Analysis Panel ──
  analysis: {
    noResults: '아직 분석 결과가 없어요',
    noResultsDesc:
      'AI 분석을 시작하면 그림 추출, 재현 파라미터, 프로세스 다이어그램까지 한눈에 볼 수 있어요.',
    progress: '분석 진행',
    phase1: 'Phase 1: 심층 논문 분석',
    phase1Desc: '방법론과 결과, 기여를 종합해서 읽어요',
    phase2: 'Phase 2: 인용 분석',
    phase2Desc: '참고문헌을 정리하고 인용 빈도를 분석해요',
    phase3: 'Phase 3: 그림 & 데이터 추출',
    phase3Desc: '그림과 표, 시각 데이터를 모두 뽑고 해석해요',
    phase4: 'Phase 4: 재현성 레시피',
    phase4Desc: '실험 파라미터와 프로토콜을 자세히 뽑아요',
    phase5: 'Phase 5: 시각화 & 종합',
    phase5Desc: '프로세스 다이어그램과 시각 요약을 만들어요',
    analyzingDots: '분석 중...',
    loadingResults: '결과를 불러오고 있어요...',
    rewriteLevel: '설명 수준',
    rewriting: '수준에 맞게 다시 쓰는 중...',
    rewriteFailed: '재작성에 실패했습니다. 다시 시도해주세요.',
    // formatPhaseAsMarkdown labels
    md: {
      domain: '분야',
      relevance: '관련도',
      methodology: '방법론',
      complexity: '복잡도',
      experimental: '실험적',
      hasFigures: '그림 포함',
      agent: '에이전트',
      yes: '예',
      no: '아니오',
      keyTopics: '핵심 주제',
      figures: '그림',
      tables: '표',
      equations: '수식',
      diagramTypes: '다이어그램 유형',
      keyFindings: '핵심 발견',
      statisticalRedFlags: '⚠️ 통계적 Red Flags',
      redFlagSeverity: { high: '높음', medium: '보통', low: '낮음' },
      redFlagTypes: {
        no_error_bars: '오차막대 미표기',
        insufficient_n: '샘플 수 부족',
        axis_manipulation: '축 스케일 조작 의심',
        cherry_picking: 'Cherry-picking 의심',
        no_statistical_significance: '통계 유의성 미언급',
        misleading_scale: '오해 유발 스케일',
      } as Record<string, string>,
      confidence: '신뢰도',
      reproducibility: '재현성',
      parameters: '파라미터',
      paramNum: '#',
      paramName: '파라미터',
      paramValue: '값',
      paramUnit: '단위',
      paramNotes: '비고',
      materials: '재료',
      equipment: '장비',
      experimentalSteps: '실험 단계',
      criticalNotes: '핵심 주의사항',
      missingInfo: '누락된 정보',
      expectedResults: '예상 결과',
      safetyNotes: '안전 주의사항',
      novelty: '신규성',
      comparisonToPrior: '기존 연구 비교',
      strengths: '강점',
      weaknesses: '약점',
      suggestedImprovements: '개선 제안',
      practicalApplications: '실용적 적용',
      followUpQuestions: '후속 질문',
    },
  },

  // ── Progress Tracker ──
  progressTracker: {
    title: '분석 진행',
    running: '실행 중',
    complete: '완료',
    phase1: 'Phase 1',
    phase1Desc: '스크리닝',
    phase2: 'Phase 2',
    phase2Desc: '인용 분석',
    phase3: 'Phase 3',
    phase3Desc: '시각 검증',
    phase4: 'Phase 4',
    phase4Desc: '레시피',
    phase5: 'Phase 5',
    phase5Desc: '심층 분석',
  },

  // ── Figures ──
  figures: {
    title: '추출한 그림',
    noFigures: '이 논문에서 뽑은 그림이 아직 없어요.',
    preparing: 'Figure를 준비하고 있어요. 잠시 후 자동으로 새로고침해요.',
    syncing: '최신 Figure를 백그라운드에서 동기화하고 있어요.',
    partialWarning: '최신 Figure를 아직 동기화하고 있어요. 지금까지 저장한 결과를 먼저 보여줘요.',
    expertExplanation: '전문가 상세 설명',
    explanationFailed: '설명을 만들지 못했어요',
    retry: '다시 시도',
    explanationLoading: 'AI가 그림을 분석하고 있어요...',
    clickForExplanation: '그림을 누르면 AI 전문가가 자세히 설명해요.',
    prevFigure: '이전 그림',
    nextFigure: '다음 그림',
    close: '닫기',
    viewDetail: (name: string) => `${name} 상세 보기`,
    qualityHigh: '고화질',
    qualityMedium: '보통',
    qualityLow: '저화질',
    qualityUnknown: '알 수 없음',
    confidence: (score: string) => `신뢰도 ${score}`,
    statusUncertain: '불확실',
    statusReady: '확정',
    composite: 'Composite',
    jumpToPage: 'PDF 페이지로 이동',
    childGroup: (count: number) => `서브피겨 ${count}개`,
    provenanceLabel: (model: string) => `분류 ${model}`,
  },

  // ── Tables ──
  tables: {
    title: '추출한 표',
    noTables: '이 논문에서 뽑은 표가 아직 없어요.',
    preparing: 'Table을 준비하고 있어요. 잠시 후 자동으로 새로고침해요.',
    syncing: '최신 Table을 백그라운드에서 동기화하고 있어요.',
    partialWarning: '최신 Table을 아직 동기화하고 있어요. 지금까지 저장한 결과를 먼저 보여줘요.',
    confidence: (score: string) => `신뢰도 ${score}`,
    parseMethod: (method: string) => `파싱 ${method}`,
    statusUncertain: '불확실',
    statusReady: '확정',
    resolverLabel: (version: string) => `해결기 ${version}`,
    modelLabel: (model: string) => `복구 ${model}`,
    reviewRequired: '검증 필요',
    repairAttempted: '복구 시도',
    repairConfidence: (score: string) => `복구 ${score}`,
    markdownPreview: '구조화된 미리보기',
    csvAsset: 'CSV 열기',
    htmlAsset: 'HTML 열기',
    jumpToPage: 'PDF 페이지로 이동',
    pageLabel: (page: number) => `${page}페이지`,
  },

  // ── Recipe Card ──
  recipe: {
    title: '재현성 레시피',
    noRecipe: '아직 레시피를 만들지 않았어요. 분석을 실행하면 파라미터를 뽑아요.',
    exportCsv: 'CSV',
    exported: '내보냄',
    confidence: '신뢰도',
    reproducibility: '재현성',
    objective: '목적',
    materials: '재료',
    parameters: '파라미터',
    steps: '실험 단계',
    criticalNotes: '핵심 주의사항',
    missingInfo: '누락된 정보',
    noParams:
      '파라미터를 뽑지 못했어요. 논문에 실험 세부 정보가 적거나, Methods 섹션을 온전히 읽지 못했을 수 있어요.',
    expectedResults: '예상 결과',
    safetyNotes: '안전 주의사항',
  },

  // ── Mermaid Renderer ──
  mermaid: {
    title: '프로세스 다이어그램',
    notGenerated: '아직 다이어그램을 만들지 않았어요. 분석을 끝내면 프로세스 흐름을 볼 수 있어요.',
    code: '코드',
    preview: '미리보기',
    copy: '복사',
    render: '렌더링',
    reset: '초기화',
    mermaidCode: 'Mermaid 코드',
    renderFailed: '다이어그램을 그리지 못했어요',
    emptyCode: '다이어그램 코드가 비어 있어요',
    styleFallback: '스타일 구문에 오류가 있어 일부 스타일을 빼고 그렸어요',
    repairing: 'AI가 다이어그램 오류를 고치고 있어요...',
    repairedNotice: '구문 오류를 자동으로 고쳤어요',
    download: '다운로드',
    expand: '크게 보기',
    close: '닫기',
    zoomIn: '확대',
    zoomOut: '축소',
    zoomReset: '100%',
    regenerate: '다시 생성',
    regenerating: '다시 만들고 있어요...',
    regenerateFailed: '다시 만들지 못했어요',
    exportAll: '전체 다운로드',
    exporting: '내보내고 있어요...',
    exportFailed: '시각화를 내보내지 못했어요',
    visualizations: '시각화',
    generating: '시각화를 만들고 있어요...',
    generatingTime: '1~2분 걸릴 수 있어요',
    illustrationFailed: '일러스트를 만들지 못했어요',
    generationFailed: '만들지 못했어요',
  },

  // ── Toast messages ──
  toast: {
    uploadSuccess: '논문을 보관함에 추가했어요',
    uploadFailed: '논문을 보관함에 추가하지 못했어요',
    analysisStarted: '분석을 시작했어요',
    analysisComplete: '분석을 끝냈어요',
    analysisCancelled: '분석을 취소했어요',
    analysisError: '분석하는 중에 오류가 생겼어요',
    settingsSaved: '변경을 저장했어요',
    settingsFailed: '변경을 저장하지 못했어요',
    paperDeleted: '논문을 보관함에서 삭제했어요',
    deleteFailed: '논문을 삭제하지 못했어요',
    csvExported: 'CSV 파일을 내려받았어요',
    copied: '클립보드에 복사했어요',
    domainUpdated: '분야를 바꿨어요',
    agentChanged: '담당 에이전트를 변경했습니다',
    agentChangeFailed: '에이전트를 변경하지 못했습니다',
  },

  // ── Error / Fallback ──
  error: {
    occurred: '오류가 생겼어요',
    unknown: '알 수 없는 오류가 생겼어요.',
    retry: '다시 시도',
    goHome: '홈으로 돌아가기',
    devInfo: '개발자 정보 (Development Only)',
    networkError: '네트워크 연결을 확인해 주세요.',
    apiKeyMissing: '시스템 제어에서 API 키를 입력하면 분석을 시작할 수 있어요.',
    loadPapersFailed: '논문 목록을 불러오지 못했어요',
    deletePaperFailed: '논문을 삭제하지 못했어요',
    updatePaperFailed: '논문을 업데이트하지 못했어요',
    getStatusFailed: '상태를 확인하지 못했어요',
    startAnalysisFailed: '분석을 시작하지 못했어요',
    loadAnalysisFailed: '분석 결과를 불러오지 못했어요',
  },

  // ── Agent fallback ──
  agent: {
    unknownDomain: '알 수 없는 분야',
    unknownAgent: '알 수 없는 에이전트',
    fallbackQuote: '분석을 준비하고 있어요.',
  },

  // ── Titlebar ──
  titlebar: {
    minimize: '최소화',
    maximize: '최대화',
    restore: '이전 크기로',
    close: '닫기',
  },
} as const;
